name: tianshou_gpu
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.0=h996f2a0_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - decorator==5.2.1
      - deepdiff==7.0.1
      - distlib==0.4.0
      - docstring-parser==0.17.0
      - etils==1.13.0
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - fonttools==4.61.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - grpcio==1.76.0
      - gymnasium==1.2.2
      - h5py==3.15.1
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonargparse==4.44.0
      - kiwisolver==1.4.9
      - llvmlite==0.45.1
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - ml-collections==1.1.0
      - moviepy==2.2.1
      - mpmath==1.3.0
      - mujoco==3.3.7
      - networkx==3.6
      - numba==0.62.1
      - numpy==2.2.6
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.12.0.88
      - ordered-set==4.1.0
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pettingzoo==1.25.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - proglog==0.1.12
      - protobuf==6.33.1
      - pygame==2.6.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - sensai==1.6.0
      - sensai-utils==1.6.0
      - six==1.17.0
      - smmap==5.0.2
      - stable-baselines3==2.7.1
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tianshou==2.0.0
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - triton==3.3.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - virtualenv==20.35.4
      - werkzeug==3.1.4
      - zipp==3.23.0
prefix: /home/ubuntu/miniconda3/envs/tianshou_gpu
